//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Actor
    {
        public int AID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd / MMM / yyyy}")]
        [DisplayName("Date of Birth")]
        public System.DateTime DOB { get; set; }
        [DataType(DataType.MultilineText)]
        public string Bio { get; set; }
        [DisplayName("Worked ON")]
        public string workedON { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase ImageFileActor { get; set; }
        public List<MovieData> getMovieList { get; set; }

        public string[] MovieList { get; set; }
    }
}

