//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Comment
    {
        public int CID { get; set; }
        [DisplayName("Movie")]
        public int MID { get; set; }
        [DisplayName("Review")]
        [DataType(DataType.MultilineText)]
        public string Comments { get; set; }

        public virtual Movie Movie { get; set; }
    }
}

