//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class TVShow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVShow()
        {
            this.TComments = new HashSet<TComment>();
        }

        public int TID { get; set; }
        public string Name { get; set; }
        [DataType(DataType.MultilineText)]
        public string Plot { get; set; }
        public string Poster { get; set; }
        [DisplayName("Cast")]
        public string CastID { get; set; }
        [DisplayName("Release Date")]
        [DisplayFormat(DataFormatString = "{0:dd / MMM / yyyy}")]
        public System.DateTime YearOfRelease { get; set; }
        public int Rating { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        public virtual Actor Actor { get; set; }

        public List<ActorData> getActorList { get; set; }

        public string[] actorList { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TComment> TComments { get; set; }
    }
}
